# Site settings
title: Females in media
#email: your-email@domain.com
url: https://example.github.io
description: "A data-based exploration of female representation in media."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#403F4C' # dark grey-purple
  links: '#219ab3' #blue

# Footer settings
footer: ADA Fall 2021 Aibohphobia Team

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: https://twitter.com/SBootstrap
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: https://lisalrt.github.io/females-in-media/

# Build settings
markdown: kramdown
permalink: pretty
